# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-26 19:46
from __future__ import unicode_literals

import django.db.models.deletion
from django.db import migrations, models

import v6score.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Measurement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('requested', models.DateTimeField(auto_now_add=True)),
                ('started', models.DateTimeField(blank=True, null=True)),
                ('finished', models.DateTimeField(blank=True, null=True)),
                ('v4only_image', models.ImageField(blank=True, null=True, upload_to=v6score.models.my_basedir)),
                ('v6only_image', models.ImageField(blank=True, null=True, upload_to=v6score.models.my_basedir)),
                ('nat64_image', models.ImageField(blank=True, null=True, upload_to=v6score.models.my_basedir)),
                ('v6only_score', models.FloatField(default=-1)),
                ('nat64_score', models.FloatField(default=-1)),
            ],
        ),
        migrations.CreateModel(
            name='Website',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hostname', models.CharField(max_length=128, unique=True, validators=[v6score.models.validate_hostname])),
                ('hash_param', models.CharField(blank=True, max_length=128)),
            ],
        ),
        migrations.AddField(
            model_name='measurement',
            name='website',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='v6score.Website'),
        ),
    ]
