# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-10 13:11
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('v6score', '0006_auto_20160929_1531'),
    ]

    operations = [
        migrations.RenameField(
            model_name='measurement',
            old_name='nat64_score',
            new_name='nat64_image_score',
        ),
        migrations.RenameField(
            model_name='measurement',
            old_name='v6only_score',
            new_name='v6only_image_score',
        ),
    ]
