# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-10 13:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('v6score', '0007_auto_20161010_1311'),
    ]

    operations = [
        migrations.AddField(
            model_name='measurement',
            name='nat64_resource_score',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='measurement',
            name='v6only_resource_score',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
