# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-24 10:27
from __future__ import unicode_literals

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('v6score', '0008_auto_20161010_1312'),
    ]

    operations = [
        migrations.AddField(
            model_name='measurement',
            name='dns_results',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.GenericIPAddressField(), blank=True, default=list, size=None),
        ),
        migrations.AddField(
            model_name='measurement',
            name='ping_1500_latencies',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(), blank=True, default=list, size=None),
        ),
        migrations.AddField(
            model_name='measurement',
            name='ping_latencies',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(), blank=True, default=list, size=None),
        ),
    ]
