# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-24 11:12
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('v6score', '0009_auto_20161024_1027'),
    ]

    operations = [
        migrations.RenameField(
            model_name='measurement',
            old_name='ping_1500_latencies',
            new_name='ping4_1500_latencies',
        ),
        migrations.RenameField(
            model_name='measurement',
            old_name='ping_latencies',
            new_name='ping4_latencies',
        ),
    ]
