# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-11-20 15:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('v6score', '0012_auto_20161025_1009'),
    ]

    operations = [
        migrations.AddField(
            model_name='measurement',
            name='url',
            field=models.URLField(blank=True),
        ),
    ]
