# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-11-20 15:23
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('v6score', '0013_measurement_url'),
    ]

    operations = [
        migrations.RunSQL("update v6score_measurement set url=("
                          "select 'http://'||hostname from v6score_website where v6score_website.id=website_id"
                          ") where url='';")
    ]
