# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-11-20 17:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('v6score', '0015_auto_20161120_1634'),
    ]

    operations = [
        migrations.AlterField(
            model_name='measurement',
            name='url',
            field=models.URLField(),
        ),
    ]
