# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-11-23 14:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('v6score', '0017_auto_20161121_1938'),
    ]

    operations = [
        migrations.AddField(
            model_name='measurement',
            name='latest',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.RunSQL("UPDATE v6score_measurement "
                          "SET latest=true "
                          "WHERE id IN ("
                          "SELECT first_value(id) OVER (PARTITION BY url ORDER BY finished DESC) "
                          "FROM v6score_measurement WHERE finished IS NOT NULL);",
                          "")
    ]
